# Generated by Django 3.0.3 on 2020-09-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celebrity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('intro', models.CharField(max_length=1000)),
                ('imgSrc', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=10)),
                ('movies', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('rating', models.FloatField(max_length=10)),
                ('summary', models.CharField(max_length=1000)),
                ('imgSrc', models.CharField(max_length=200)),
                ('comment1', models.CharField(max_length=1000)),
                ('comment2', models.CharField(max_length=1000)),
                ('comment3', models.CharField(max_length=1000)),
                ('comment4', models.CharField(max_length=1000)),
                ('comment5', models.CharField(max_length=1000)),
                ('actors', models.CharField(max_length=1000)),
            ],
        ),
    ]
